### ISSUE TITLE
`ml demo colorize` failed

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlmodels#31]
commit 37dcb7ba78ae780050c97e28943f236c1c54c7c5

```console
$ ml demo colorize
Colorize /home/simon/.mlhub/colorize/images/image_01_bw.png
An error was encountered:

/anaconda/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 19, in <module>
    out = predict(gray)
  File "/home/simon/.mlhub/colorize/utils.py", line 16, in predict
    model = load_model(model_path)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/keras/engine/saving.py", line 250, in load_model
    f = h5py.File(filepath, mode='r')
  File "/anaconda/envs/py35/lib/python3.5/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'models/model.08-5.7380.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by gjwgit** [comment]
Fixed.
