### ISSUE TITLE
MOVIE RECOMMENDER: Please update DESCRIPTIONS to current mlhub format

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlmodels#36]
The commands section no longer has a description field. Use sentences also for the commands now. See iris for example. Currently getting this error:

```
$ ml commands movie-recommender
The model 'movie-recommender' (movie recommendation using SAR package)
supports the following commands:

$ ml print movie-recommender
Traceback (most recent call last):
  File "/anaconda/envs/py35/bin/ml", line 11, in <module>
    sys.exit(main())
  File "/anaconda/envs/py35/lib/python3.5/site-packages/mlhub/__init__.py", line 189, in main
    args.func(args)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/mlhub/commands.py", line 392, in list_model_commands
    print("  " + info['commands'][c])
TypeError: Can't convert 'collections.OrderedDict' object to str implicitly
```

**Comment by ZhouFang928** [comment]
updated and close.
